FROM eddyded49/udg_space_ubuntu:latest

RUN apt-get update -y && apt-get upgrade -y

# 
RUN apt -y install xfce4 
RUN apt -y install xfce4-goodie

RUN cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
RUN sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini
RUN sed -i 's/max_bpp=32/#max_bpp=32\nmax_bpp=128/g' /etc/xrdp/xrdp.ini
RUN sed -i 's/xserverbpp=24/#xserverbpp=24\nxserverbpp=128/g' /etc/xrdp/xrdp.ini
RUN echo xfce4-session > ~/.xsessionxfce4-goodie

CMD bash